<script  type="text/javascript">

beforeready = function(){
         tpl.localizer.submits.en="Vote!";
        $('input#temp-EMEA-Customer1').addClass('mktFReq');

}

ready = function(){

$('<p class="formText">Choose your reseler:</p>').insertBefore('input#temp-EMEA-Customer1').parent();
$('<p class="formText">Please introduce yourself:</p>').prependTo('li:has(#FirstName)');


$.getScript('http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js' ,function() {
    var availableCompany = [
"ARNIAS",
"Aurelium NV",
"AXI NV",
"B-INSIDE",
"BKM",
"Business Network Systems",
"Cegeka NV",
"CELEM",
"Centix",
"CEVI",
"Cheops Technology nv",
"Christiaens Computer Service NV",
"COMPAREX Belgium",
"Computacenter NV",
"COMPUTERLAND S.L.M. S.A.",
"Computers and Communications NV",
"Econocom Belgium",
"I.R.I.S. ICT",
"Insight Technology Solutions Belgium",
"Into IT",
"IT1",
"LB Computer Systems",
"LNS NV",
"netflow bvba",
"Nexis",
"NSI IT Software & Services",
"OPNS S.A.",
"Orbid NV",
"Proterm Systems NV",
"RealDolmen",
"REDCORP",
"SA BULL NV",
"SAVACO NV",
"Schaubroeck Informatica",
"Systemat Belgium",
"Trustteam",
"VanRoey.be",
"WASLET IT",
"Xylos",
"ePact NV",
"2Bit",
"3-it",
"4Business Software",
"AbAKUS it-solutions",
"ABSI",
"Accel",
"Add-On sprl",
"Akacio",
"Alandra BVBA",
"Alfa Solutions",
"All Information Technology",
"Allmas IT Solutions",
"Amster Group",
"ANS Computer",
"Anymatik",
"AnySys ICT",
"Apchard nv",
"AppSys ICT Group",
"ARCATECH",
"Arphan SPRL",
"Assign NV",
"ASSYST EUROPE",
"ATA IT BVBA",
"ATOS BELGIUM NV",
"Atri Services",
"Avitor",
"Axio Systems",
"B.I.T. Solutions GCV",
"Bechtle Comsoft",
"Bechtle Direct N.V.",
"Belgacom Bridging ICT N.V./ Interconnect",
"Belgian Network Soluitions bvba",
"Berox",
"BISOFT",
"Bitcon",
"Bits4kmo",
"BJ IT",
"Boek & Soft",
"BRO-Consulting",
"BZM Services BVBA",
"Cel term Services",
"Centric Belgium NV",
"CLEW BVBA",
"Cloud computer company",
"Cloud Concepts",
"CMC bvba",
"CMV Solutions bvba",
"Comase Info S.A.",
"Compuboek",
"COMPUSELECT BVBA",
"COMPUTER COMPTA SYSTEMS",
"ConXioN",
"Coppens Hofman N.V.",
"CP SOLUTIONS CV",
"Crystal IT",
"Cybernet",
"termcore bvba",
"DB Services",
"DCI IT Management",
"delphi solutions bvba",
"Devocom NV",
"DIGI Belgium nv",
"DigiPoint NV",
"Dimension term",
"Driezen Computers",
"DVEsoft",
"DVIT",
"Dyv OceanWeB",
"E.S.I Informatique",
"Easycom BVBA",
"Easynext",
"EB Concept BVBA",
"Econoweb B.V.B.A",
"EFFIX Group",
"EG Top Professionals BVBA",
"Elektromic",
"EMOND BVBA",
"ESC",
"Eulogic",
"Eurosys nv",
"Exabyte BVBA",
"Exemplis BVBA",
"ExsIT SPRL",
"FERRANTI COMPUTER SYSTEMS NV",
"Financial Art S.A.",
"Fintan IT",
"FLAG 2000",
"FLEXOS ICT BELGIUM sa",
"Fonitel NV",
"Foxconcept",
"FrameIT",
"Fujitsu Belgium",
"Fundit BVBA",
"Future Telecom - NT Security Group",
"G&T Services",
"GENERAL MASTER BUSINESQS",
"Getronics Belgium",
"GIETECO",
"Glonet NV",
"Greenock CAD Service Belgium NV",
"Group AC",
"Groupe Open Belgium",
"Hendrickx Kreative bvba",
"Hobb-IT",
"HP Belgium",
"I.R.I.S. Luxembourg",
"IBS bvba",
"IBS Consulting",
"ICASA ICT Solutions",
"ICTB-Associates",
"ictvoorkmo",
"ICT-Worx BVBA",
"IDS Service",
"IECK SPRL",
"IF-IT4U bvba",
"InformAdvies bvba",
"Infront Consulting Group BVBA",
"Integrated Quality Networks",
"INTERCARE NV",
"INTERIT NV",
"InterOffice Sobete Tongeren BVBA",
"Iptor",
"Isabel NV",
"ISIS",
"IT Designs BVBA",
"IT SYSTEMS BVBA",
"IT4C",
"IT-BRAIN",
"ITCE",
"Itigate BVBA",
"IT-SC",
"ITWEBOFFICE",
"I-Way Computers bvba",
"iXL-iT",
"IZIT bvba",
"JFK Computersystems",
"Joba IT Solutions BVBA",
"KALIX ICT COUNSELLORS",
"Karibou Informatique",
"KIDA Solutions",
"Kinneq bvba",
"KKSYS n.v.",
"KPD Services NV",
"Laurenterprise BVBA",
"limelogic",
"Logix Benelux (they do not distribute VMware anymore)",
"Lubon bvba",
"LUX INFORMATIQUE",
"MAARO BVBA",
"MCG",
"MCH",
"Megabyte NV",
"Micro Computer Service Center bvba",
"Microware Solutions N.V.",
"MIND MANAGEMENT CONSULTING",
"MNC BVBA",
"M-STUDIO",
"MVconcepts",
"MY Services SA",
"Myriade NV",
"NET COMPUTER GROUP SA",
"netex",
"Netmind sprl",
"Netsearch Consulting",
"Netshield",
"NETsite SA",
"NET-Worx BVBA",
"NUCLEUS",
"O.S.G. bvba",
"ODIT NV",
"OLILEO",
"OPENIX BVBA",
"ORBIT ONE",
"Orditech",
"PC Cleaning & Tools bvba",
"PC INFO-SERVICE BVBA",
"PCSOL SA",
"PhiMAC Consult BVBA",
"Pluritech",
"Post ICT bvba",
"PPC Solutions",
"Proact Belgium",
"PROIT4ALL S.P.R.L.",
"PROSTEPS",
"Prosum bvba",
"pvconsulting",
"Raxco Software Belgium & France",
"R-eBus C&D BVBA",
"Remmicom",
"ROVACON BVBA",
"Rubik Solutions bvba",
"Saande",
"Safe-ICT",
"Sagamgraphic",
"SAIT Zenitel",
"Samandar bvba",
"SBIM",
"SDE NV",
"SeBeGo Computers Alken",
"SecureLink nv",
"ServCat",
"Server Storage Solutions",
"Servitweb",
"Setelco NV",
"Sherwood S.A.",
"Shinka IT",
"SIP",
"Sitax",
"Skoezie bvba",
"SLAMM bvba",
"Smartsys",
"Snijders Compuservice bvba",
"Sogeti Belgium",
"Spravtek",
"STONEZ",
"STS",
"StudioFrancine.com",
"syncware",
"Systeam Computers bvba",
"T-Bench",
"TDC3 V.O.F.",
"Tech Session",
"Techne IT Solutions BVBA",
"Telesafe NV",
"TFE Electronics BVBA",
"THV HP/BELGACOM",
"Training and Services",
"Trasys",
"t-Sphere",
"UCW Computers BVBA",
"Universal Network Solutions SCRL",
"UNIWAN.BE SPRL",
"Valco Soft bvba",
"Van Hessen N.V.",
"V-Consult",
"Vdestra Technics",
"Vercruysse bvba",
"Virtacon",
"Vision COnsulting group",
"WICE bvba",
"WoCom",
"XILA IT BVBA",
"Youcom BVBA",
"2serve bvba",
"Acom",
"ADENTI NV",
"Adifo NV",
"Ahead-IT",
"Alpha3S NV",
"ALSIC BVBA",
"Altair SA",
"Axentys",
"AXIANS",
"be.wan",
"Cats and Dogs BVBA",
"CBM Moerman",
"Chameleon",
"CISA",
"Comitor",
"Connectis",
"CRM.tec",
"Damnet SCRL",
"termplan Informatica bvba",
"denk-it bvba",
"DirectIT BVBA",
"Disprimo N.V.",
"Drive IT",
"EASI",
"ECX",
"Entrypoint",
"Extra IT",
"Falcon Automation",
"Genius Technology Solutions",
"Herithos NV",
"INCRIUS",
"Integreat NV.",
"IT Anywhere",
"IT PARTNER BVBA",
"ITC Belgium",
"IT-LOGICS",
"Lebon IT Services",
"Little Indian sprl",
"MAKARA",
"Matcom BVBA",
"Mobile Access",
"NETXPERT",
"Nubera BVBA",
"Office-IT",
"P&G Consulting",
"PC Center BVBA",
"PCS Computer Knokke",
"Plus IT",
"Raido BVBA",
"Secure IT",
"Sercu NV",
"Serso",
"Simac Belgium",
"Summer-House SPRL",
"Syncron",
"SYNERGY INFORMATTIC SA",
"System Solutions Belgium",
"Tigron BVBA",
"Trinsy Technics bvba",
"UPFRONT",
"Willux.be NV",
"XPOWER",
"CBC Informatique S.A",
"GLOBAL IT SERVICES",
"Netcore PSF",
"System Solutions Luxembourg S.A.",
"Systemat Luxembourg PSF sa",
"Telindus Luxembourg",
"Agil-IT SA",
"AUDITSERV Sarl",
"Broadcasting Center Europe",
"CEL - VOICE & term Communications",
"Computacenter PSF SA",
"CTG Luxembourg",
"CTTL SA",
"Dell S.A.",
"DEVOTEAM Guidance S.A.",
"dsl Data Service Luxembourg",
"ELGON SA",
"FACILITY-TRADE Sarl",
"Fujitsu Technology Solutions S.A. Luxembourg",
"GES Luxembourg",
"G-sysinformatique",
"InfoServ",
"in-visible",
"LXCDM Computer and Network Solutions",
"M.I.T Sarl",
"Open Field",
"OpenV-IT",
"PLT Automation S.a r.L",
"SCHNEIDER IT MANAGEMENT SARL",
"Seven Layers",
"Simac PSF S.A.",
"Sogeti Luxembourg",
"STERIA PSF",
"tecsys IT-Haus s.a.",
"Telecom Luxembourg",
"TELEPHONIE s.a.",
"TUOMI SA",
"INFODATA S.àr.l.",
"Real Solutions S.A.",
"TechIT PSF S.A."
    ];

    $("#temp-EMEA-Customer1").autocomplete({
      source: availableCompany,
	   matchContains:false, 
        minChars:1,  
        autoFill:false, 
        mustMatch:true, 
    });
  });
}

</script>